services:
  api:
    image: ghcr.io/saleor/saleor:3.23
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - cache
    volumes:
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,127.0.0.1,api

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.23
    ports:
      - 9000:80
    restart: unless-stopped

  db:
    image: library/postgres:15-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - POSTGRES_DB=saleor

  cache:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.23
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - cache
      - db
    volumes:
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,127.0.0.1,api

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
